# Generated by Django 5.0.6 on 2024-05-10 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poliza', models.CharField(max_length=20)),
                ('asegurado', models.CharField(max_length=20)),
                ('cuit', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cuil', models.CharField(max_length=20)),
                ('id_poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scvo.poliza')),
            ],
        ),
    ]
